import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// components
import Header from "./components/layouts/Header";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Astarabica",
  description: "Generated by Ananda",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {/* Header */}
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
